In [1]:
import numpy as np
from sklearn import preprocessing
import pandas as pd

In [28]:
train_data=np.genfromtxt("power_plant_train.csv",delimiter=",")
test_data=np.genfromtxt("power_plant_test.csv",delimiter=",")
print(train_data.shape)
print(test_data.shape)
x_train=train_data[:,:4]
y_train=train_data[:,4:]
x_test=test_data[:,:]
#x_train=np.append(x_train,np.ones((x_train.shape[0],1)),axis=1)
#x_test=np.append(x_test,np.ones((x_test.shape[0],1)),axis=1)
print(x_train)





(7176, 5)
(2392, 4)
[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]


In [29]:
scaler_x=preprocessing.StandardScaler()
scaler_x.fit(x_train)
x_train=scaler_x.transform(x_train)
x_test=scaler_x.transform(x_test)

x_train=np.append(x_train,np.ones((x_train.shape[0],1)),axis=1)
x_test=np.append(x_test,np.ones((x_test.shape[0],1)),axis=1)
print(x_train)

[[-1.47827466e+00 -1.24764165e+00  1.30221067e+00  7.58624590e-01
   1.00000000e+00]
 [ 2.89012041e-01  3.06797549e-01  6.61749044e-01 -4.46921842e-01
   1.00000000e+00]
 [-3.99975582e-01 -4.21012529e-01 -2.87207194e-01  3.75010552e-01
   1.00000000e+00]
 ...
 [ 1.36062192e+00  1.18048335e+00 -6.54382840e-01 -5.83682640e-01
   1.00000000e+00]
 [-4.36097263e-01  9.29089763e-04  7.84140927e-01 -6.59584883e-01
   1.00000000e+00]
 [ 1.40209496e+00  6.07960340e-01 -4.31394890e-01 -1.73110573e+00
   1.00000000e+00]]


In [30]:
def sgd(x_train,y_train,learning_rate,m):
    m_slope=np.zeros(x_train.shape[1])
    n=len(x_train)
    for i in range(n):
        x=x_train[i]
        y=y_train[i]
        ans=0
        for k in range(x_train.shape[1]):
            ans+=m[k]*x[k] 
        for j in range(x_train.shape[1]):
            m_slope[j]+=(-2/n)*(y-ans)*x[j]
    new_m=m-learning_rate*m_slope
    return new_m

In [31]:
def gd(x_train,y_train,learning_rate,iterations):
    m=np.zeros(x_train.shape[1])
    for i in range(iterations):
        m=sgd(x_train,y_train,learning_rate,m)
        if(i%10==0):
            print(i,"cost is ",cost(x_train,y_train,m))
    return m

In [32]:
def cost(x_train,y_train, m):
    total_cost = 0
    M = len(x_train)
    for i in range(M):
        x = x_train[i]
        y = y_train[i]
        total_cost+= (1/M)*((y - (m*x).sum())**2)

    return total_cost

In [33]:
def run():
    learning_rate=0.1
    iterations=500
    m=gd(x_train,y_train,learning_rate,iterations)

    return m

In [35]:
m=run()
print(m)
n=len(x_test)
y=np.zeros(n)
print("y shape is",y.shape)
for i in range(n):
    x=x_test[i]
    y[i]=(m*x).sum()
finalans=y
np.savetxt("power_plant_prediction.csv", finalans,delimiter = ",",fmt='%1.5f')


0 cost is  [132273.17028198]
10 cost is  [1552.76219376]
20 cost is  [43.19370474]
30 cost is  [24.17601062]
40 cost is  [22.93725513]
50 cost is  [22.25217118]
60 cost is  [21.80013752]
70 cost is  [21.50059001]
80 cost is  [21.3020477]
90 cost is  [21.17044917]
100 cost is  [21.08322227]
110 cost is  [21.02540598]
120 cost is  [20.98708383]
130 cost is  [20.9616829]
140 cost is  [20.9448465]
150 cost is  [20.93368689]
160 cost is  [20.92629001]
170 cost is  [20.92138716]
180 cost is  [20.91813742]
190 cost is  [20.91598341]
200 cost is  [20.91455568]
210 cost is  [20.91360933]
220 cost is  [20.91298208]
230 cost is  [20.91256631]
240 cost is  [20.91229073]
250 cost is  [20.91210807]
260 cost is  [20.911987]
270 cost is  [20.91190675]
280 cost is  [20.91185356]
290 cost is  [20.9118183]
300 cost is  [20.91179493]
310 cost is  [20.91177944]
320 cost is  [20.91176917]
330 cost is  [20.91176237]
340 cost is  [20.91175786]
350 cost is  [20.91175487]
360 cost is  [20.91175289]
370 cost is 